### ISSUE TITLE
Proposed Removal of Wiki Pages

### ISSUE THREAD

**Issue by germonprez** [OSSHealth/ghdata#18]
Hi all, 

I'd like to propose that we move the Wiki pages to their own .md documents in the /docs folder. This was a recommendation from several folks here but primarily those who are actively using GH to build out communities. The suggestion is that Wiki pages are just not a very highly used or observed part of GH and that keeping things in files like this allows for better tracking through pull requests.

**Comment by howderek** [comment]
I agree that Markdown files are better but it's important to keep in mind these files will be distributed to those who download our package. We should limit which documents appear in `docs/` to only those that are relevant to users and developers of GHData. I think discussion and planning should happen elsewhere.

**Comment by GeorgLink** [comment]
We could move the md files to OSSHealth/HealthIndicators - our project
management repository.

**Comment by germonprez** [comment]
Fair enough on limiting the files in docs/. However, GHData needs to express things beyond the technical details. If we are going to build out the community, we need to express things like the roadmap. Perhaps scale back the roadmap.md file to only include technical and outreach goals. Move the academic things out and into the papers.md file (to be moved to HealthIndicators)

For the queries, I imagine that we will have a queries.py file at sometime. As queries.md stands right now, I'm fine with it in the docs/ folder.

**Comment by howderek** [comment]
@germonprez Yes, of course. I agree with your proposal about the roadmap.

The queries appear in [ghdata.py](https://github.com/OSSHealth/ghdata/blob/master/ghdata/ghdata.py) when they are implemented.

**Comment by germonprez** [comment]
@howderek -- Roger on ghdata.py!
