### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by germonprez** [OSSHealth/ghdata#45]
I can never ever seem to get this installed on a fresh install. I always end up with 404 errors. The install seems fine but when I fire up the server, things just don't come up on the browser. This happens a lot to me. 

Also, opendata.missouri.edu seems to be timing out. It is possible this is me as I'm at a community center doing this.

**Comment by howderek** [comment]
@germonprez Does [this new README](https://github.com/OSSHealth/ghdata/blob/dev/README.md) help? If not, let me know how I can make it more clear.

**Comment by germonprez** [comment]
Sorry for the delay. Install ran cleanly. 

Remind me again what the test URL is.

**Comment by howderek** [comment]
It will depend. DId you use docker or without docker? It should log the ports either way, but it may have gotten pushed up by the other text. The default port for the API is 5000

**Comment by sgoggins** [comment]
The read me file is going to include a developer deployment instruction set and a docker deployment instruction set. This is targeted for end of October.

**Comment by sgoggins** [comment]
@howderek and @ChristianCme : I want to resolve this by doing a clean deploy on an empty server and updating our documentation to reflect what you learn here.
