### ISSUE TITLE
Rewire GHData-CHAOSS Metric Description Links

### ISSUE THREAD

**Issue by sgoggins** [OSSHealth/ghdata#50]
The metrics committee changed the links on the wiki, but many of the links are dead. 

As an example, the 'community activity' link on the current ghdata deployment:  http://ghdata.sociallycompute.io/?repo=rails+rails 

under the "community activity" graph at the top, links here: https://wiki.linuxfoundation.org/oss-health-metrics/metrics/community-activity 

Which links to a dead github link, here: https://github.com/chaoss/metrics/blob/master/metrics/community-activity.md 

I think we do need links for EACH metric pointing to specific MD files on the CHAOSS Repository. 

@GeorgLink : I think this is yours, but let's start a discussion.

**Comment by GeorgLink** [comment]
Thank you for pointing this out, I already forgot about the old wiki pages :-D

I can fix the dead links on the wiki.

**Comment by GeorgLink** [comment]
I did my part and fixed all the links.

I propose that GHdata links to the new location directly because I want the old wiki pages to go away.

**Comment by sgoggins** [comment]
Hi @GeorgLink : OK, this seems like it would not be a big deal.  In the wiki, there used to be one link per metric.  Does a corrallary exist in the CHAOSS GH Repository?

Thanks!  @howderek  & @ChristianCme  .. just a heads up on this discussion. :)

**Comment by GeorgLink** [comment]
Yes and No:

Yes:
All pages that were in the wiki continue to exist in GitHub.

No:
We only have metric detail pages for those metrics where Anna developed SQL
statements.
Most metrics never had a page of their own because we had nothing to put on
them - feel free to create new metric detail pages as you are implementing
them.

**Comment by sgoggins** [comment]
@howderek and @ChristianCme : I think this is done, yes?
