### ISSUE TITLE
Fix Docker Deployment for New Front end release

### ISSUE THREAD

**Issue by sgoggins** [OSSHealth/ghdata#58]
@howderek : 👍

**Comment by howderek** [comment]
This is more involved than I expected because I forgot that our current Docker setup uses the MSR14 dataset and not the full GHTorrent dataset. 

@sgoggins should I remove the database from docker-compose and have the docker application provide only the frontend and backend without the database, or should we consider this an open issue until the full GHTorrent dataset is deployable with our docker-compose application?

**Comment by GeorgLink** [comment]
> or should we consider this an open issue until the full GHTorrent dataset is deployable with our docker-compose application?

Are you proposing to include the database inside the docker container?
If I understood that correctly, I think the first option is superior. 

A docker container that includes the database has two major issues:
1. Size
2. Requires updating when new data is released

**Comment by sgoggins** [comment]
Yes. Have the database separate. 

Sean P. Goggins
(816) 368-1364
http://www.seangoggins.net
visit: http://www.sociotech.net
visit: http://www.datafactories.org 

"I force people to have coffee with me, just because I don't trust that a friendship can be maintained without any other senses besides a computer or cellphone screen.”
— John Cusack


On Dec 22, 2017, at 07:29, Derek Howard <notifications@github.com> wrote:

This is more involved than I expected because I forgot that our current Docker setup uses the MSR14 dataset and not the full GHTorrent dataset.

@sgoggins should I remove the database from docker-compose and have the docker application provide only the frontend and backend without the database, or should we consider this an open issue until the full GHTorrent dataset is deployable with our docker-compose application?

**Comment by sgoggins** [comment]
I think keeping the database out of the docker is best. We can Provide another Docker container for the database if needed.  

Sean P. Goggins
(816) 368-1364
http://www.seangoggins.net
visit: http://www.sociotech.net
visit: http://www.datafactories.org 

"I force people to have coffee with me, just because I don't trust that a friendship can be maintained without any other senses besides a computer or cellphone screen.”
— John Cusack


On Dec 22, 2017, at 08:00, Georg J.P. Link <notifications@github.com> wrote:

or should we consider this an open issue until the full GHTorrent dataset is deployable with our docker-compose application?

Are you proposing to include the database inside the docker container?
If I understood that correctly, I think the first option is superior.

A docker container that includes the database has two major issues:

Size
Requires updating when new data is released

**Comment by sgoggins** [comment]
This works now. Currently in Dev and Master.
