### ISSUE TITLE
Install with Docker environment variables

### ISSUE THREAD

**Issue by b-hodges** [OSSHealth/ghdata#78]
In step 2 of the instructions for Installation with Docker it says to configure the environment variables. It does not say where to set the environment variables. Should they be set in the docker-compose.yml file? And if so, should the README say that?

**Comment by howderek** [comment]
Set the environment variables in the standard UNIX way:
```bash
export GHDATA_DB_USER="ghdata"
```

I will make that more clear. The blank variables in docker-compose mean "use whatever is set on the host system"

https://docs.docker.com/compose/compose-file/#environment

I recommend not setting these variable in the docker-compose.yml directly but instead setting them at runtime or by sourcing a script that sets the variables (such as a ~/.profile)

**Comment by sgoggins** [comment]
I agree with the solution of making this explicit in the README file.  @b-hodges  and @germonprez : For the other docker images you are deploying, how is this handled? Are they using the docker-compose.yml or local environment variables as Derek suggests?  Not trying to parse "right" or "wrong", but instead trying to understand how this is being done in other corners of the CHAOSS ecosystem. :)

**Comment by b-hodges** [comment]
I started out using the local environment but changed to docker-compose.yml to test it. They seem to achieve the same results, but using local environment variables doesn't require changing a tracked file. I've updated the #79 pull request to reflect this, clarifying some of the wording about the local environment variables.

**Comment by sgoggins** [comment]
@b-hodges : Do you consider this closed once the pull request is accepted?

**Comment by b-hodges** [comment]
That works. I'll close this issue then.

**Comment by sgoggins** [comment]
@howderek : Please merge the pull request ... I am going to reopen and figure out how to attache an issue to a pull request if this is not already done.

**Comment by sgoggins** [comment]
... and, nevermind ...@howderek merged the pull request . :)
