### ISSUE TITLE
Adding License Identifiers

### ISSUE THREAD

**Issue by germonprez** [OSSHealth/ghdata#8]
Hey all, I'd like to add SPDX license identifiers to all source files

# SPDX-License-Identifier: MIT

**Comment by GeorgLink** [comment]
@howderek you merged #9, #12 and #13, can this issue be closed?

PS: GitHub can [automatically close issues](https://help.github.com/articles/closing-issues-via-commit-messages)

**Comment by howderek** [comment]
@GeorgLink Yes! Thanks.
