### ISSUE TITLE
Issue times series endpoint

### ISSUE THREAD

**Issue by sgoggins** [OSSHealth/ghdata#89]
```json
/timeseries/issues/full
[
    {
        "date": "2015-01-01T00:00:00.000Z",
        "opened": 4,
        "closed": 1,
        "comments": 11,
        "response_time": 24,
        "resolution_time": 72,
    },
    ...
]
```

**Comment by howderek** [comment]
I have the same questions about this as I do about #90.

**Comment by GeorgLink** [comment]
Please don't make me look at another issue for a question, just post it
again. Referencing issues is great for dependencies.

My answer is: We have not talked about this on the metrics committee. I
say, make a good guess and see how helpful it is. It'll be easier to change
those settings after they are implemented.
​

**Comment by howderek** [comment]
I'll make it configurable.

**Comment by gordongli** [comment]
Perhaps a parameter for a running total or for the timeframe (e.g. a week)
