### ISSUE TITLE
Pull Request time Series Full

### ISSUE THREAD

**Issue by sgoggins** [OSSHealth/ghdata#90]
```json
/timeseries/pulls/full
[
    {
        "date": "2015-01-01T00:00:00.000Z",
        "opened": 4,
        "closed": 1,
        "merged": 2,
        "comments": 11,
        "acceptance_rate": 0.5,
        "response_time": 24,
        "resolultion_time": 72
    },
    ...
]
```

**Comment by howderek** [comment]
Should `opened` and `closed` represent the number of PRs opened and closed that day, or running totals? Over what time frame should the `acceptance_rate`, `response_time`, and `resolution_rate` be calculated?

**Comment by GeorgLink** [comment]
We have not talked about this on the metrics committee. I say, make a good
guess and see how helpful it is. It'll be easier to change those settings
after they are implemented.

**Comment by howderek** [comment]
I'll make it configurable.
